Warehouse/Models/WareHouse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class WareHouse
    {
        public string Id { get; set; }

        [StringLength(20, MinimumLength = 3, ErrorMessage = "*The number of warehouse must be between 3 and 20 characters")]
        [Required(ErrorMessage = "*The field is not filled")]
        public string Number { get; set; }
        
        [Required(ErrorMessage = "*The field is not filled")]
        [StringLength(20, MinimumLength =3, ErrorMessage = "*The adress must be between 3 and 20 characters")]
        public string Address { get; set; }

        public bool IsActive { get; set; }
        public DateTime CreationDate { get; set; }
    }
}

Warehouse/Controllers/WareHouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using PagedList.Core;
using Warehouse.Data;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WareHouseController : Controller
    {
        readonly ILogger<WareHouseController> _log;

        private readonly ApplicationDbContext _context;
        public WareHouseController(ApplicationDbContext context, ILogger<WareHouseController> log,
        ILogger<WareHouseController> logger)
        {
            _log = logger;
            _context = context;
        }

        public IActionResult Index(string number, string address, int page = 1, int pageSize = 10)
        {
            if (!FilterValid()) return BadRequest();
            var query = _context.Warehouses.AsQueryable().OrderBy(d => d.CreationDate);
            if (!string.IsNullOrEmpty(number))
                query = query.Where(w => w.Number.Contains(number, StringComparison.InvariantCultureIgnoreCase)).OrderBy(d => d.CreationDate);
            if (!string.IsNullOrEmpty(address))
                query = query.Where(w => w.Address.Contains(address, StringComparison.InvariantCultureIgnoreCase)).OrderBy(d=>d.CreationDate);
            ViewData["CurrentNumber"] = number;
            ViewData["CurrentAddress"] = address;
            ViewData["CurrentSize"] = pageSize;
            PagedList<WareHouse> model = new PagedList<WareHouse>(query, page, pageSize);
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            _log.LogInformation("Warehouse index. "+user);
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(WareHouse wh)
        {
            if (_context.Warehouses.FirstOrDefault(w => w.Number == wh.Number) != null)
                ModelState.AddModelError("", "The number of warehouse already exists");
            if (ModelState.IsValid)
            {
                wh.IsActive = true;
                wh.CreationDate = DateTime.Now;
                _context.Add(wh);
                _context.SaveChanges();
                var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                _log.LogInformation("Created warehouse.User: "+user);
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Edit(string id)
        {
            var obj = _context.Warehouses.Find(id);
            if (obj == null) return BadRequest();
            return View(obj);
        }

        [HttpPost]
        public IActionResult Edit(WareHouse wh)
        {
            if (_context.Warehouses.FirstOrDefault(w => w.Number == wh.Number && w.Id != wh.Id) != null)
                ModelState.AddModelError("", "The number of warehouse already exists");
            if (ModelState.IsValid)
            {
                _context.Warehouses.Update(wh);
                _context.SaveChanges();
                var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                _log.LogInformation("Edited warehouse.User: "+user);
                return RedirectToAction("Index");
            }
            return View();
        }
        

        
        [HttpPost]
        public JsonResult Disable([FromBody]string warehouseId)
        {
            var data = _context.Warehouses.Find(warehouseId);
            if (data == null || !data.IsActive) return Json(false);
            var productManagers = _context.ProductManagers.Where(pm => pm.WareHouseId == warehouseId);
            foreach(var item in productManagers)
            {
                if (item.CurrentCount != 0) return Json(false);
            }
            data.IsActive = false;
            _context.Warehouses.Update(data);
            _context.SaveChanges();
            return Json(true);
        }

        [HttpPost]
        public JsonResult Enable([FromBody]string warehouseId)
        {
            var data = _context.Warehouses.Find(warehouseId);
            if (data == null || data.IsActive) return Json(false);
            data.IsActive = true;
            _context.Update(data);
            _context.SaveChanges();
            return Json(true);
        }
        [NonAction]
        bool FilterValid()
        {
            if (Request.Query.Count != 0)
            {
                var keys = Request.Query.Keys;
                var request = Request.Query;
                if (keys.Contains("PageSize"))
                    if (!(byte.TryParse(request["PageSize"], out byte size) && size > 0 && size < 101)) return false;
                if (keys.Contains("Page"))
                    if (!(uint.TryParse(request["Page"], out uint page) && page > 0)) return false;
            }
            return true;
        }
    }
}

Warehouse/Views/WareHouse/Create.cshtml
@model Warehouse.Models.WareHouse
@using Warehouse.Resources
@{
    ViewData["Title"] = "Create";
}
@inject LocService SharedLocalizer
<h2>Create new warehouse</h2>
<form style="width:50%" asp-action="create" asp-controller="WareHouse" method="post" asp-antiforgery="true">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Number">@SharedLocalizer.GetLocalizedHtmlString("NumberOfWarehouse")</label>
            <input type="text" asp-for="Number" class="form-control"/>
            <span asp-validation-for="Number"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="Address">@SharedLocalizer.GetLocalizedHtmlString("Address")</label>
            <input asp-for="Address" type="text" class="form-control" />
            <span asp-validation-for="Address"></span>
        </div>
        <div>
            <input type="submit" value="Create" class="btn" />
        </div>
</form>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Warehouse/Views/WareHouse/Edit.cshtml
@model Warehouse.Models.WareHouse
@{
    ViewData["Title"] = "Edit";
}
@using Warehouse.Resources

@inject LocService SharedLocalizer
<form asp-action="Edit" asp-controller="WareHouse" method="post" asp-antiforgery="true">
    <div>
        <input type="hidden" asp-for="IsActive"/>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <label asp-for="Number">@SharedLocalizer.GetLocalizedHtmlString("NumberOfWarehouse")</label>
            <input type="text" asp-for="Number" class="form-control" />
            <span asp-validation-for="Number"></span>
        </div>
        <div class="form-group">
            <label asp-for="Address">@SharedLocalizer.GetLocalizedHtmlString("Address")</label>
            <input asp-for="Address" type="text" class="form-control" />
            <span asp-validation-for="Address"></span>
        </div>
        <div><input type="submit" value="Edit" class="btn btn-primary" /></div>
    </div>
</form>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Warehouse/Views/WareHouse/Index.cshtml
@using Warehouse.Models

@{
    ViewData["Title"] = "Index";
}
@model IPagedList<WareHouse>
@using Warehouse.Resources

@inject LocService SharedLocalizer

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<form method="get" asp-action="Index">
    <div class="form-inline form-group">
        <label class="control-label">@SharedLocalizer.GetLocalizedHtmlString("WarehouseNumber") </label>
        <input class="form-control" type="text" name="number" value="@ViewData["CurrentNumber"]" />

        <label class="control-label">@SharedLocalizer.GetLocalizedHtmlString("WarehouseAddress") </label>
        <input class="form-control" type="text" name="address" value="@ViewData["CurrentAddress"]" />

        <label class="control-label">@SharedLocalizer.GetLocalizedHtmlString("PageSize")</label>
        <input class="form-control" type="number" min="1" max="100" name="pageSize" value="@ViewData["CurrentSize"]" />
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
</form>
<br />
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Number")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Address")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Edit")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Disable")</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr><td colspan="8" class="text-center">@SharedLocalizer.GetLocalizedHtmlString("There are no warehouses!")</td></tr>
            }
            @{
                foreach (var wh in Model)
                {
                    <tr>
                        <td hidden="hidden"><input type="hidden" value="@wh.Id" /></td>
                        <td>@wh.Number</td>
                        <td>@wh.Address</td>
                        <td><a class="edited btn" asp-action="Edit" asp-route-id="@wh.Id">@SharedLocalizer.GetLocalizedHtmlString("Edit") <i class="fas fa-pen-square ml-1"></i></a></td>
                        @if (@wh.IsActive == true)
                        {
                            <td><a href="#" class="Disable btn">@SharedLocalizer.GetLocalizedHtmlString("Disable")</a></td>
                        }
                        else
                        {
                            <td><a href="#" class="Enable btn">@SharedLocalizer.GetLocalizedHtmlString("Enable")</a></td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>
    </div>
    <pager list="@Model" asp-route-pageSize="@ViewData["CurrentSize"]" asp-route-number="@ViewData["CurrentNumber"]" asp-route-address="@ViewData["CurrentAddress"]" asp-controller="WareHouse" asp-action="Index" />


    @section scripts{
        <link href="~/css/jquery.contextMenu.css" rel="stylesheet" />
        <script src="~/js/jquery.contextMenu.js"></script>
        <script src="~/js/jquery.ui.position.js"></script>
        <link href="~/css/jquery-confirm.min.css" rel="stylesheet" />
        <script src="~/js/jquery-confirm.min.js"></script>
        <script>
            $("[href='#']").on("click", function () {
                let $link = $(this);
                $(this).parent().parent().addClass(".select");
                $link.addClass('context-menu-one');
                $.contextMenu({
                    selector: '.context-menu-one',
                    trigger: 'left',
                    callback: function (key, options) {
                    },
                    position: function (opt, x, y) {
                        opt.$menu.css({ top: y + 10, left: x - 90 });
                    },
                    items: {
                        "Yes": {
                            name: "Yes", icon: "fas fa-check-circle",
                            callback: function (key, options) {
                                let $link = $(this);
                                let $row = $(this).parent().parent().addClass(".select");
                                let warehouseId = $row.children().children().val();
                                if ($link.text() === 'Enable') {
                                    $.ajax({
                                        url: '/WareHouse/Enable',
                                        type: "POST",
                                        data: JSON.stringify(warehouseId),
                                        contentType: "application/json; charset=utf-8",
                                        dataType: "json",
                                        async: false,
                                        success: function (data) {
                                            if (data) {
                                                $.confirm({
                                                    icon: 'fas fa-check-circle',
                                                    title: 'Warehouse!',
                                                    content: 'Warehouse has been activated!',
                                                    type: 'dark',
                                                    typeAnimated: true,
                                                    closeAnimation: 'rotateXR',
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-dark",
                                                            action: function () {
                                                                $link.text("Disable").attr("class", "Disable btn");
                                                            }
                                                        }
                                                    }
                                                });
                                                $row.removeClass();
                                            }
                                            else {
                                                $.confirm({
                                                    icon: 'fas fa-exclamation-triangle',
                                                    title: 'Warehouse!',
                                                    content: 'An error occurred. There may be products left in warehouse. Please, try again!',
                                                    type: 'red',
                                                    typeAnimated: true,
                                                    closeAnimation: 'rotateXR',
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-red",
                                                            action: function () {
                                                                $link.text("Enable").attr("class", "Enable btn");
                                                            }
                                                        }
                                                    }
                                                });
                                            }
                                        }
                                    })
                                }
                                else if ($link.text() === 'Disable') {
                                    $.ajax({
                                        url: '/WareHouse/Disable',
                                        type: "POST",
                                        data: JSON.stringify(warehouseId),
                                        contentType: "application/json; charset=utf-8",
                                        dataType: "json",
                                        async: false,
                                        success: function (data) {
                                            if (data) {
                                                $.confirm({
                                                    icon: 'fas fa-check-circle',
                                                    title: 'Warehouse',
                                                    content: 'Warehouse has been deactivated!',
                                                    type: 'dark',
                                                    typeAnimated: true,
                                                    closeAnimation: 'rotateXR',
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-dark",
                                                            action: function () {
                                                                $link.text("Enable").attr("class", "Enable btn");
                                                            }
                                                        }
                                                    }
                                                });
                                                $row.removeClass();
                                            }
                                            else {
                                                $link.text("Disable").css("color", "red");
                                                $.confirm({
                                                    icon: 'fas fa-exclamation-triangle',
                                                    title: 'Warehouse',
                                                    content: 'An error occurred. There may be products left in warehouse. Please, try again!',
                                                    type: 'red',
                                                    typeAnimated: true,
                                                    closeAnimation: 'rotateXR',
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-red",
                                                            action: function () {
                                                                $link.text("Disable").attr("class", "Disable btn");
                                                            }
                                                        }
                                                    }
                                                });
                                            }
                                        }
                                    })
                                }
                                $row.removeClass();
                            }
                        },
                        "sep1": "---------",
                        "Cansel": { name: "Cansel", icon: 'far fa-times-circle' }
                    }
                });

            });
        </script>
    }