Warehouse/Models/Basket.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class Basket
    {
        public string Id { get; set; }
        public uint Count { get; set; }
        public DateTime AddDate { get; set; }

        public string ProductId { get; set; }
        public Product Product { get; set; }

        public string UserId { set; get; }
        public AppUser User { get; set; }
        public string WarehouseId { get; set; }
        public WareHouse WareHouse { get; set; }
 
    }
}

Warehouse/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;
using Warehouse.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace Warehouse.Controllers
{
    [Authorize(Roles = "Worker")]
    public class BasketController : Controller
    {
        private readonly ApplicationDbContext _context;
        readonly ILogger<BasketController> _log;

        public string MemberShip { get; private set; }

        public BasketController(ApplicationDbContext context, ILogger<BasketController> log)
        {
            _log = log;
            _context = context;
        }
        public IActionResult ChangeCount(string id, string count)
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var basket = _context.Baskets.Find(id);
            basket.Count = Convert.ToUInt32(count);
            _context.Baskets.Update(basket);
            _context.SaveChanges();
            var baskets = _context.Baskets.Include(p => p.Product).Where(p => p.UserId == user.Id);
            return View("_Index", baskets);
        }
        public IActionResult Index()
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            //todo
            var baskets = _context.Baskets.Include(p => p.Product).Where(p=>p.UserId == user.Id).ToList();
            _log.LogInformation("Basket index. User: "+user);
            return View("_Index", baskets);
        }
        public IActionResult IndexForHover()
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            //todo
            var baskets = _context.Baskets.Include(p => p.Product).Where(p => p.UserId == user.Id);
            _log.LogInformation("Basket index.User: "+user);
            return View("_IndexForHover", baskets);
        }
        [HttpPost]
        public IActionResult DeleteYes(string id)
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var baskets2 = _context.Baskets.Include(p => p.Product).Where(p => p.UserId == user.Id);
            var obj = _context.Baskets.FirstOrDefault(b=>b.Id == id);
            if(obj!=null)
                _context.Baskets.Remove(obj);
            _context.SaveChanges();
            
            _log.LogInformation("Deleted basket item."+user);
            var baskets = _context.Baskets.Include(p => p.Product).Where(p => p.UserId == user.Id);
            _log.LogInformation("Basket index.User: " + user);
            return View("_IndexForHover", baskets);
        }
    }
}

Warehouse/Views/Basket/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@using Warehouse.Resources

@inject LocService SharedLocalizer
<h2>@SharedLocalizer.GetLocalizedHtmlString("Delete")</h2>
<p>@SharedLocalizer.GetLocalizedHtmlString("Delete")?</p>

<a asp-action="DeleteYes" asp-controller="Basket" asp-route-id="@Model.Id">@SharedLocalizer.GetLocalizedHtmlString("Yes")!</a>
<a asp-action="Index" asp-controller="Basket">@SharedLocalizer.GetLocalizedHtmlString("No")!</a>

Warehouse/Views/Basket/IndexForHover.cshtml
@model IEnumerable<Warehouse.Models.Basket>
@{
    Layout = null;
}


@{if (Model.Count() > 0)
    {
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Count</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pb in Model)
                {
                <tr>
                    <td>@pb.Product.Name</td>
                    <td>@pb.Count</td>
                    <td><a asp-action="Delete" asp-route-id="@pb.Id">Delete</a></td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No products to show!</p>
    }
}

Warehouse/Views/Basket/_Index.cshtml
@model IEnumerable<Warehouse.Models.Basket>
@{
    ViewData["Title"] = "Index";
}

@*<table class="table table-bordered table-hover">
        <thead class="bg-primary">
            <tr>
                <th>Name</th>
                <th>Count</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @{if (Model.Count()>0 && Model!=null)
                {

                    foreach (var pb in Model)
                    {
                    <tr>
                        <td>@pb.Product.Name</td>
                        <td>@pb.Count</td>
                        <td><a asp-action="Delete" asp-route-id="@pb.Id">Delete</a></td>
                    </tr>
                    }
                }
                else
                {
                    <p>No products to show!</p>
                }

                }
        </tbody>
    </table>*@
<partial name="../Basket/_IndexForHover" />
@{
    if (Model.Count() > 0)
    {
        <a asp-controller="Order" asp-action="Create" class="btn btn-default" id="chekOutBtn">Check out</a>
    }
}
@*@Html.Partial("_IndexForHover");*@

Warehouse/Views/Basket/_IndexForHover.cshtml
@model IEnumerable<Warehouse.Models.Basket>
@{
    Layout = null;
}


<script src="~/js/jquery.contextMenu.js"></script>
<link href="~/css/jquery.contextMenu.css" rel="stylesheet" />
<link href="~/css/jquery-confirm.min.css" rel="stylesheet" />
<script src="~/js/jquery-confirm.min.js"></script>
<script src="~/js/jquery.ui.position.js"></script>

@{if (Model.Count() > 0)
    {
        <script>
            $("#chekOutBtn").removeAttr("disabled");
            $("#chekOutBtn").css('pointer-events', 'all');
        </script>
        <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Count</th>
                        <th>Change count</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var pb in Model)
                    {
                        
                        <tr>
                            <td>@pb.Product.Name</td>
                            <td class="countOfBasketProduct">@pb.Count</td>
                            <td><a class="changeCountOrder edited btn" href="#">Change <i class="fas fa-pen-square ml-1"></i><input type="hidden" value="@pb.Id" class="changeInputValue" /></a></td>
                            <td><a href="#" class="deleted btn">Delete <i class="fas fa-times ml-1"></i><input type="hidden" value="@pb.Id" class="deletedValue" /></a></td>
                        </tr>
                    }
                </tbody>
            </table>
            </div>
            }
            else
            {
            <p>No products to show!</p>
            <script>
                $("#chekOutBtn").attr('disabled', 'true');
                $("#chekOutBtn").css('pointer-events', 'none');
            </script>
            }
            }
            <script>
                $(() => {
                    $(".deleted").click(function () {
                        let $link = $(this);
                        $link.addClass('context-menu-one');
                        $.contextMenu({
                            selector: '.context-menu-one',
                            trigger: 'left',
                            callback: function (key, options) {
                            },
                            position: function (opt, x, y) {
                                opt.$menu.css({ top: y + 10, left: x - 90 });
                            },
                            items: {
                                "Yes": {
                                    name: 'Yes', icon: 'fas fa-check-circle',
                                    callback: function () {
                                        var basketItemId = $(this).children(".deletedValue").val();
                                        var basketItem = $(this).parent().parent();
                                        let $link = $(this);
                                        $.ajax({
                                            url: '@Url.Action("DeleteYes", "Basket")',
                                            type: "POST",
                                            data: { 'id': basketItemId },
                                            async: false,
                                            success: function (result) {
                                                basketItem.remove();
                                                if (result) {
                                                    $.confirm({
                                                        icon: 'fas fa-check-circle',
                                                        title: 'Warehouse!',
                                                        content: "Item removed from basket",
                                                        type: 'dark',
                                                        typeAnimated: true,
                                                        buttons: {
                                                            close: {
                                                                btnClass: "btn-dark",
                                                                action: function () {
                                                                    basketItem.remove();
                                                                }
                                                            }
                                                        }

                                                    });
                                                   
                                                }
                                                else {
                                                    $.confirm({
                                                        icon: 'fas fa-exclamation-triangle',
                                                        title: 'Warehouse!',
                                                        content: 'An error occurred. Please, try again!',
                                                        type: 'red',
                                                        typeAnimated: true,
                                                        buttons: {
                                                            close: {
                                                                btnClass: "btn-red",
                                                                action: function () {
                                                                }
                                                            }
                                                        }
                                                    });
                                                }
                                            }
                                        });
                                        $link.removeClass("context-menu-one");
                                        basketItemId = "";
                                    }
                                },
                                "sep1": "---------",
                                "Cansel": { name: "Cansel", icon: 'far fa-times-circle' }
                            }
                        });

                    });
                    $(".changeCountOrder").click(function () {
                        var $Id = $(this).children(".changeInputValue").val();
                        var $c = $(this).parent().parent().children(".countOfBasketProduct");
                        $.confirm({
                            title: 'Write out!',
                            content: '' +
                                '<div class="form-group">' +
                                '<label>Change count!</label>' +
                                '<input type="number" placeholder="0" min="1" id="countChangeInput" class="form-control"/>' +
                                '</div>',
                            buttons: {
                                formSubmit: {
                                    text: 'Ok',
                                    action: function () {
                                        var $Count = $("#countChangeInput").val();
                                        if ($Count == 0) {
                                            $.confirm({
                                                icon: 'fas fa-exclamation-triangle',
                                                content: 'An error has occurred. Write the actual amount!',
                                                type: 'red',
                                                typeAnimated: true,
                                                buttons: {
                                                    close: {
                                                        btnClass: "btn-red",
                                                        action: function () {
                                                        }
                                                    }
                                                }
                                            });
                                            return false;
                                        }
                                        $.ajax({
                                            type: "POST",
                                            data: {
                                                id: $Id,
                                                count: $Count
                                            },
                                            async: false,
                                            url: "../../Basket/ChangeCount",
                                            success: function (result) {
                                                $c.text($Count);
                                                if (result) {
                                                    error = false;
                                                    $.confirm({
                                                        icon: 'fas fa-check-circle',
                                                        title: 'Basket',
                                                        content: 'Count changed!',
                                                        type: 'blue',
                                                        typeAnimated: true,
                                                        buttons: {
                                                            close: {
                                                                btnClass: "btn-blue",
                                                                action: function () {
                                                                }
                                                            }
                                                        }
                                                    });
                                                }
                                            }
                                        });
                                    }
                                },
                                cancel: function () {
                                    //close
                                },
                            }
                        });
                    });
                });
            </script>