Warehouse/Models/ProductManager.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class ProductManager
    {
        
        public string Id { get; set; }
        [Required(ErrorMessage = "*The field is not filled")]
        [RegularExpression("([1-9][0-9]{0,15})", ErrorMessage = "*Invalid value")]
        public uint Count { get; set; }
        public uint CurrentCount { get; set; }

        [Required(ErrorMessage = "*The field is not filled")]
        [RegularExpression("([1-9][0-9]{0,15})", ErrorMessage = "*Invalid value")]
        public decimal ReceiptPrice { get; set; }

        [Required(ErrorMessage = "*The field is not filled")]
        [RegularExpression("([1-9][0-9]{0,15})", ErrorMessage = "*Invalid value")]
        public decimal SalePrice { get; set; }
        public DateTime ReceiptDate { get; set; }
        public DateTime Date { get; set; }
        public string UserId { get; set; }
        public AppUser User { get; set; }
        public string WareHouseId { get; set; }
        public WareHouse WareHouse { get; set; }
        [Required]
        public string ProductId { get; set; }
        public Product Product { get; set; }
        public bool IsWriteOut { get; set; } = false;
    }
}

Warehouse/Controllers/ProductManagerController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;
using Warehouse.HtmlHelper;
using Warehouse.Models;
using PagedList.Core;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Logging;
using Warehouse.Infrastructure;

namespace Warehouse.Controllers
{
    [Authorize(Roles = "Storekeeper, Worker")]
    public class ProductManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        readonly ILogger<ProductManagerController> _log;

        public ProductManagerController(ApplicationDbContext context, ILogger<ProductManagerController> log)
        {
            _log = log;
            _context = context;
        }


        ///// <summary>
        ///// Show product manager group by product
        ///// </summary>
        ///// <param name="type">Product type</param>
        ///// <param name="name">Product name</param>
        ///// <param name="page">Current page. Default page 1</param>
        ///// <param name="pageSize">Page size. Default size 10</param>
        /// <returns></returns>
        public IActionResult Index(ProductManagerViewModel viewModel)
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var li = new List<WareHouse>();
            foreach (var wh in _context.AppUserWareHouses.Where(u => u.AppUserId == user.Id))
            {
                li.Add(_context.Warehouses.Find(wh.WareHouseId));
            }
            //var a = _context.Users.Include(u => u.WareHouses);
            if (!FilterValid()) return BadRequest();
            //var userik =  _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            
            var query = _context.ProductManagers.Include(w => w.WareHouse).Include(p => p.Product.ProductType)
                .Include(p => p.Product.Unit).AsQueryable()
                .Where(pm => li.Contains(_context.Warehouses.FirstOrDefault(w=>w.Id == pm.WareHouseId)) && pm.Product.IsActive);
            if (viewModel.TypeId != null)
                if (_context.Types.Find(viewModel.TypeId) != null)
                    query = query.Where(pm => pm.Product.ProductTypeId == viewModel.TypeId);
                else return BadRequest();
            if (viewModel.ProductId != null)
                if (_context.Products.Find(viewModel.ProductId) != null)
                    query = query.Where(pm => pm.ProductId == viewModel.ProductId);
                else return BadRequest();
            if (viewModel.WarehouseID != null)
                query = query.Where(pm => pm.WareHouseId == viewModel.WarehouseID);
            var queryGroup=query.GroupBy(pm=>pm.Product).Select(item => new
                       {
                           Product = item.Key,
                           Count = item.Sum(p => p.Count),
                           CurrentCount = item.Sum(p => p.CurrentCount)
                       }).Select(c=>c.ToExpando());
            ViewBag.paged = new PagedList<ExpandoObject>(queryGroup, viewModel.Page, viewModel.PageSize);
            ViewBag.Types = new SelectList(_context.Types.Where(pt => pt.IsActive), "Id", "Name");
            ViewBag.Products = new SelectList(_context.Products.Where(p => p.IsActive), "Id", "Name");
            

            ViewBag.WareHouses = new SelectList(li, "Id", "Number");
            _log.LogInformation("Product manager index.User: " + user);
            return View(viewModel);
        }

        /// <summary>
        /// Open the create product manager window
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Storekeeper")]
        [HttpGet]
        public IActionResult Create()
        {
            SelectInitial();
            return View();
        }



        /// <summary>
        /// Create new productManager
        /// </summary>
        ///// <param name="productManager">ProductManager object</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(ProductManager productManager)
        {
            SelectInitial();
            if (string.IsNullOrEmpty(productManager.ProductId))
            {
                ModelState.AddModelError("","The product type or product name not selected");
            }
            if (ModelState.IsValid)
            {
                var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
                var product = _context.Products.Include(u => u.Unit).FirstOrDefault(p => p.Id == productManager.ProductId);
                productManager.Date = DateTime.Now;
                productManager.UserId = user.Id;
                productManager.CurrentCount = productManager.Count;
                productManager.Product = product;
               // productManager.WareHouseId = user.WarehouseId;
                _context.Add(productManager);
                _context.SaveChanges();
                _log.LogInformation("Product manager created.User: " + user);
                return RedirectToAction("Index");
            }
            return View(productManager);
        }



        /// <summary>
        /// Initial the select box
        /// </summary>
        void SelectInitial()
        {
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var li = new List<WareHouse>();
            foreach (var wh in _context.AppUserWareHouses.Where(u => u.AppUserId == user.Id))
            {
                li.Add(_context.Warehouses.Find(wh.WareHouseId));
            }
            
            ViewBag.WareHouses = new SelectList(li, "Id", "Number");
            ViewBag.Products = new SelectList(_context.Products, "Id", "Name");
            ViewBag.ProductTypes = new SelectList(_context.Types, "Id", "Name");
        }

        

        /// <summary>
        /// Show all product managers
        /// </summary>
        ///// <param name="id">Product id</param>
        ///// <param name="from">Date from</param>
        ///// <param name="before">Date before</param>
        ///// <param name="page">Current page. Default 1</param>
        ///// <param name="pageSize">Page size. Default 10</param>
        /// <returns></returns>
        public IActionResult Show(string id, decimal from, decimal before, int page=1, int pageSize=10)
        {
            if (!FilterValid()) return BadRequest();
            decimal data;
            if (before == 0)
            {
                data = _context.ProductManagers.Max(p => p.SalePrice);
            }
            else data = before;
            ViewData["CurrentId"] = id;
            ViewData["CurrentFrom"] = from;
            ViewData["CurrentBefore"] = before;
            ViewData["CurrentSize"] = pageSize;
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var maxPrice = _context.ProductManagers.Max(p => p.SalePrice);
            var minPrice = _context.ProductManagers.Min(p => p.SalePrice);
            var products = _context.ProductManagers
                .Where(p => p.ProductId == id &&// p.WareHouseId==user.WarehouseId &&
                 p.SalePrice>=from && p.SalePrice<=data)
                .Include(p=>p.Product)
                .Include(u=>u.Product.Unit)
                .Include(w=>w.WareHouse)
                .AsQueryable();
            PagedList<ProductManager> model = new PagedList<ProductManager>(products, page, pageSize);
            _log.LogInformation("Product manager show.User "+user);
            return View(model);
        }

        /// <summary>
        /// Open the edit ProductManager window
        /// </summary>
        ///// <param name="id">ProductManager Id</param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Edit(string id)
        {
            var productManager = _context.ProductManagers.Find(id.ToString());
            if(productManager!=null)
                return View(productManager);
            return RedirectToAction("Index");
        }

        ///// <summary>
        ///// Edit the ProductManager receipt and sale price
        ///// </summary>
        ///// <param name="productManager">ProductManager object</param>
        ///// <returns></returns>
        ///// 

        [HttpPost]
        public IActionResult Edit(ProductManager productManager)
        {
            var data= _context.ProductManagers.AsNoTracking().Where(p => p.ProductId == productManager.ProductId)
                .Include(p => p.Product).ToList();
            var prodManager = _context.ProductManagers.AsNoTracking()
                .FirstOrDefault(pm => pm.Id == productManager.Id);
            prodManager.ReceiptPrice = productManager.ReceiptPrice;
            prodManager.SalePrice = productManager.SalePrice;
            _context.Update(prodManager);
            _context.SaveChanges();
            var user = _context.Users.Find(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            _log.LogInformation("Product manager edited.User: "+user);
            return RedirectToAction("Show", new Dictionary<string, string> { { "id", prodManager.ProductId} });
        }



        ///// <summary>
        ///// Add products to the basket
        ///// </summary>
        ///// <param name="id">ProductManager Id</param>
        ///// <param name="quantity">Number of products</param>
        ///// <returns></returns>
        [HttpPost]
        public IActionResult Add(string id, string quantity, string prodManId)
        {
            if(prodManId!=null)
                ViewBag.BasketPMId = prodManId;

Warehouse/Views/ProductManager/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
@model ProductManager
@using Warehouse.Resources

@inject LocService SharedLocalizer
@{
    var date = DateTime.Now.ToString("yyyy-MM-dd");
}
<h1>@SharedLocalizer.GetLocalizedHtmlString("CreateProductManager")</h1>
<form onsubmit="return Stop()" asp-action="Create" asp-antiforgery="true">
    <div>
        <div asp-validation-summary="All"></div>
        <div id="TypeDiv" class="form-group">
            <label>@SharedLocalizer.GetLocalizedHtmlString("ProductType")</label>
            <select id="type" class="form-control" asp-items="ViewBag.ProductTypes">
                <option selected disabled value="">@SharedLocalizer.GetLocalizedHtmlString("SelectType")</option>
            </select>
        </div>
        <div id="NameDiv" class="form-group">
            <label asp-for="ProductId">@SharedLocalizer.GetLocalizedHtmlString("ProductName")</label>
            <select asp-for="ProductId" class="form-control" asp-items="ViewBag.Products">
                <option value="">@SharedLocalizer.GetLocalizedHtmlString("SelectName")</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="Count">@SharedLocalizer.GetLocalizedHtmlString("Count")</label>
            <input asp-for="Count" type="number" class="form-control" placeholder="0" min="0" />
            <span asp-validation-for="Count"></span>
        </div>
        <div class="form-group">
            <label asp-for="ReceiptPrice">@SharedLocalizer.GetLocalizedHtmlString("ReceiptPrice")</label>
            <input asp-for="ReceiptPrice" class="form-control" placeholder="0" />
            <span asp-validation-for="ReceiptPrice"></span>
        </div>
        <div class="form-group">
            <label asp-for="SalePrice">@SharedLocalizer.GetLocalizedHtmlString("SalePrice")</label>
            <input asp-for="SalePrice" class="form-control" placeholder="0" />
            <span asp-validation-for="SalePrice"></span>
        </div>
        <div class="form-group">
            <label asp-for="ReceiptDate">@SharedLocalizer.GetLocalizedHtmlString("ReceiptDate")</label>
            <input type="date" asp-for="ReceiptDate" value="@date" min="2000-01-01" max="@date" class="form-control" />
            <span asp-validation-for="ReceiptDate"></span>
        </div>
        <div class="form-group">
            <label asp-for="WareHouseId">@SharedLocalizer.GetLocalizedHtmlString("Warehouse")</label>
            <select asp-for="WareHouseId" class="form-control" asp-items="ViewBag.WareHouses">
                <option value="">@SharedLocalizer.GetLocalizedHtmlString("Warehouse")</option>
            </select>
        </div>
        <div><input id="create" type="submit" value="Create" class="btn btn-primary" /></div>
    </div>
</form>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/productManager.js"></script>
}

Warehouse/Views/ProductManager/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@using Warehouse.Resources

@inject LocService SharedLocalizer
@model Warehouse.Models.ProductManager
<form asp-action="Edit">
    <div>
        <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ProductId" />
            <label asp-for="ReceiptPrice">@SharedLocalizer.GetLocalizedHtmlString("ReceiptPrice")</label>
            <input asp-for="ReceiptPrice" asp-format="{0:#}" class="form-control" />
            <span asp-validation-for="ReceiptPrice"></span>
        </div>
        <div class="form-group">
            <label asp-for="SalePrice">@SharedLocalizer.GetLocalizedHtmlString("SalePrice")</label>
            <input asp-for="SalePrice" asp-format="{0:#}" class="form-control" />
            <span asp-validation-for="SalePrice"></span>
        </div>
        <div><input type="submit" class="btn btn-primary" value="Edit" /></div>
    </div>
</form>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Warehouse/Views/ProductManager/Index.cshtml
@*@model IPagedList<dynamic>*@
@model  ProductManagerViewModel
@{
    ViewData["Title"] = "Index";
}
@using Warehouse.Resources

@inject LocService SharedLocalizer
<form method="get" asp-action="Index">
    <div class="form-inline form-group">
        <select asp-for="TypeId" asp-items="ViewBag.Types">
            <option selected value="">All types</option>
        </select>

        <select asp-for="ProductId" asp-items="ViewBag.Products">
            <option selected value="">All products</option>
        </select>

        <select asp-for="WarehouseID" asp-items="ViewBag.Warehouses">
            <option selected value="">All products</option>
        </select>

        <label class="control-label">@SharedLocalizer.GetLocalizedHtmlString("PageSize")</label>
        <input class="form-control" type="number" min="1" asp-for="PageSize" />

        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
</form>
<br />
<div class="table-responsive">
    <table id="pmTable" class="table table-bordered">
        <thead>
            <tr>
                <th>@SharedLocalizer.GetLocalizedHtmlString("ProductType")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("ProductName")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Count")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("CurrentCount")</th>
                <th>@SharedLocalizer.GetLocalizedHtmlString("Unit")</th>
                @if (User.IsInRole("Worker"))
                {
                    <th>@SharedLocalizer.GetLocalizedHtmlString("AddToBasket")</th>
                }
                <th>@SharedLocalizer.GetLocalizedHtmlString("Show")</th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.paged.Count == 0)
            {
                <tr><td colspan="8" class="text-center">@SharedLocalizer.GetLocalizedHtmlString("ThereAreNoProducts")</td></tr>
            }
            @foreach (dynamic productManager in ViewBag.paged)
            {
                if (productManager.CurrentCount != 0)
                {
                <tr>
                    <td hidden="hidden"><input id="id" type="hidden" value="@productManager.Product.Id" /></td>
                    <td class="secondTd">@productManager.Product.ProductType.Name<input id="pmIdInp" type="hidden"  /><input type="hidden" id="basketpmId" value="@ViewBag.BasketPMId" /></td>
                    <td>@productManager.Product.Name</td>
                    <td>@productManager.Count</td>
                    <td class="currentCount">@productManager.CurrentCount</td>
                    <td>@productManager.Product.Unit.Name</td>
                    @if (User.IsInRole("Worker"))
                    {
                        <td><a class="Added btn btn-info btn-rounded btn-waves-effect waves-light">@SharedLocalizer.GetLocalizedHtmlString("Add") <i class="fas fa-plus-square ml-1"></i></a></td>
                        <td style="padding-top: 20px;"><a class="showik btn btn-rounded btn-waves-effect waves-light" asp-action="Show" asp-route-id="@productManager.Product.Id">Show</a></td>
                    }
                    else
                    {
                        <td style="padding-top: 12px;"><a class="showik btn btn-rounded btn-waves-effect waves-light" asp-action="Show" asp-route-id="@productManager.Product.Id">Show</a></td>
                    }
                </tr>
                }
            }
        </tbody>
    </table>
 </div>
    <pager list="@ViewBag.paged" asp-route-WarehouseID="@Model.WarehouseID" asp-route-PageSize="@Model.PageSize" asp-route-TypeId="@Model.TypeId" asp-route-ProductId="@Model.ProductId" asp-controller="ProductManager" asp-action="Index" />

    @section Scripts{
        <link href="~/css/jquery-confirm.min.css" rel="stylesheet" />
        <script src="~/js/jquery-confirm.min.js"></script>
        <script src="~/lib/jquery/dist/chosen.jquery.min.js"></script>
        <link href="~/css/chosen.min.css" rel="stylesheet" />
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");}
        <script>
            $("#ProductId").on("chosen:ready", function (evt, params) {
                let select = $("#TypeId").children("option:selected").val();
                let name = $("#ProductId").children("option:selected").val();
                if (select !== "") {
                    GetProducts(select);
                    if (name !== "") {
                        $("#ProductId").val(name);
                        $('#ProductId').trigger("chosen:updated");
                    }
                }
            });
            $("#TypeId").chosen({
                search_contains: true,
                width: "15%"
            });
            $("#ProductId").chosen({
                search_contains: true,
                width: "15%"
            });
            $(() => {
                $("#TypeId").on("change", function () {
                    var selected = $(this).children("option:selected").val();
                    GetProducts(selected);

                });
            });
            function GetProducts(select) {
                $.ajax({
                    url: '/Products/Get',
                    type: "POST",
                    data: JSON.stringify(select),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    async: false,
                    success: function (data) {
                        $("#ProductId").empty();
                        $("#ProductId").append("<option selected value=''>All products</select>");
                        data.forEach(function (element) {
                            $("#ProductId").append("<option value=" + element.id + ">" + element.name + "</option>");
                        });
                        $("#ProductId").trigger("chosen:updated");
                    }
                })
            }
            //Add product to the basket
            $(() => {
                $("a.Added").on("click", function () {
                    var $Id = $(this).parents("tr").children("td:first").children(":input").val();
                    var thisTag = $(this).parents("tr").children("td.currentCount");
                    var $currentCount = parseInt(thisTag.html());
                    var pmId = $(this).parent().parent().children(".second").children("#pmIdInp").val();
                    var basketProdManId = $(this).parent().parent().children(".second").children("#basketpmId").val();
                    $.confirm({
                        title: 'Write out!',
                        content: '' +
                            '<div class="form-group">' +
                            '<label>Select quantity to add to cart!</label>' +
                            '<input type="number" placeholder="0" min="0" value="0"  class="quantity form-control" required />' +
                            '</div>',
                        buttons: {
                            formSubmit: {
                                text: 'Add',
                                btnClass: 'btn-dark',
                                action: function () {
                                    var $currentQuantity = parseInt(this.$content.find('.quantity').val());
                                    if (($currentQuantity > $currentCount || $currentQuantity == 0) && pmId != basketProdManId) {
                                        $.confirm({
                                            icon: 'fas fa-exclamation-triangle',
                                            title: 'Warehouse!',
                                            content: 'An error has occurred. Write the actual amount!',
                                            type: 'red',
                                            typeAnimated: true,
                                            buttons: {
                                                close: {
                                                    btnClass: "btn-red",
                                                    action: function () {
                                                    }
                                                }
                                            }
                                        });
                                        return false;
                                    }
                                    $.ajax({
                                        type: "POST",
                                        data: {
                                            id: $Id,
                                            quantity: $currentQuantity,
                                            prodManId: pmId
                                        },
                                        async: false,
                                        url: "../../ProductManager/Add",
                                        success: function (result) {
                                            if (result) {
                                                error = false;
                                                $.confirm({
                                                    icon: 'fas fa-check-circle',
                                                    title: 'Warehouse!',
                                                    content: 'Product added to cart!',
                                                    type: 'dark',
                                                    typeAnimated: true,
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-dark",
                                                            action: function () {
                                                            }
                                                        }
                                                    }
                                                });
                                            }
                                            else {
                                                error = true;
                                                $.confirm({
                                                    icon: 'fas fa-exclamation-triangle',
                                                    title: 'Warehouse!',
                                                    content: 'An error has occurred. Please, try again!',
                                                    type: 'red',
                                                    typeAnimated: true,
                                                    buttons: {
                                                        close: {
                                                            btnClass: "btn-red",
                                                            action: function () {
                                                            }
                                                        }
                                                    }
                                                });
                                            }
                                        }
                                    });
                                    if (error) return false;
                                }
                            },
                            cancel: function () {
                                //close
                            },
                        },
                    });
                });
            });
        </script>

    }

Warehouse/Views/ProductManager/WHList.cshtml
  @model IEnumerable<Warehouse.Models.WareHouse>
@{
    ViewData["Title"] = "WHList";
    Layout = null;
}

<form method="post" asp-controller="ProductManager" asp-action="Move" asp-route-IdOfPM="@ViewBag.PMId">

    <div class="form-group">
        <label>Count</label>
        <input name="count" value="" type="text" class="form-control" />
    </div>
    @foreach (var wh in Model){
        <input type="radio" name="id" value="@wh.Id" checked />
        <label>@wh.Number</label><br />
    }

    <input type="submit" class="btn" />
</form>